###########################################################################
#######                        Project Name                         #######
###########################################################################
#                                                                         #
#                                                                         #
#                                                                         #
###########################################################################

version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ## image: nginx:latest
    container_name: nginxwebproxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./dist/:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - api
##    networks:
##      - intranet
  api:
    container_name: api
    restart: always
    build: .
## aca uso expose para que no se publique
## el puerto en el host pero solo en la red interna : intranet
    expose:
      - "80"
    env_file:
      - .env
    environment:
      - PORT=80
      - NODE_ENV=development
##    networks:
##      - intranet
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    entrypoint: ["npm", "start"]

##  postgresd:
##    image: postgres:9.6
##    networks:
##      - intranet
##    env_file:
##      - variables.env
  redis:
    image: "redis:alpine"
    container_name: redis
##    networks:
##      - intranet

##volumes:
##  storage1:
##  storage2:
##  storage3:
##  storage4:

##networks:
##  intranet:
##    driver: bridge
